# CD
# 1. main 브랜치로 온 PR이 merge
# 2. 린트,테스트,빌드 <--- Vercel 자동배포는 비활성화.
# 3. Vercel 배포

name: Continuous Delivery
on:
  pull_request:
    branches:
      - main
    types:
      - closed # merged, closed

env:
  NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}

jobs:
  lint-test-build:
    name: Lint,Test And Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Download Codes
        uses: actions/checkout@v4

      - name: Install Deps
        run: npm ci

      - name: Lint
        run: npm run lint

        # main 브랜치에서는  e2e 테스트 위주
      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

  deploy:
    name: Trigger Deploy Hook
    runs-on: ubuntu-latest
    needs: lint-test-build
    steps:
      - name: Trigger Deploy Hook
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
